version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: subastaya_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SubastaYaDb
      MYSQL_USER: subastaya_user
      MYSQL_PASSWORD: subastaya_password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: